# Generated by Django 4.2.20 on 2025-05-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meditation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("audio_file", models.FileField(upload_to="meditations/audio/")),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Duration in seconds"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("breathing", "Breathing"),
                            ("relaxation", "Relaxation"),
                            ("mindfulness", "Mindfulness"),
                            ("sleep", "Sleep"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
