# Generated by Django 4.2.20 on 2025-05-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meditation",
            name="youtube_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meditation",
            name="audio_file",
            field=models.FileField(
                blank=True, null=True, upload_to="meditations/audio/"
            ),
        ),
    ]
