# Generated by Django 4.2.20 on 2025-05-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0002_meditation_youtube_url_alter_meditation_audio_file"),
    ]

    operations = [
        migrations.RemoveField(model_name="meditation", name="audio_file",),
        migrations.AlterField(
            model_name="meditation",
            name="youtube_url",
            field=models.URLField(
                default="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
            ),
            preserve_default=False,
        ),
    ]
