# Generated by Django 4.2.20 on 2025-05-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0003_remove_meditation_audio_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meditation",
            name="youtube_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
