# Generated by Django 4.2.20 on 2025-05-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0004_alter_meditation_youtube_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="meditation",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="meditation_images/"
            ),
        ),
    ]
