# Generated by Django 4.2.20 on 2025-05-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0005_meditation_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="meditation",
            name="animation_type",
            field=models.CharField(
                blank=True,
                help_text="Тип анімації, наприклад: 'circle', 'bar'",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meditation",
            name="breathing_pattern",
            field=models.JSONField(
                blank=True,
                help_text="Наприклад: {'inhale': 4, 'hold': 7, 'exhale': 8}",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meditation",
            name="instruction",
            field=models.TextField(
                blank=True, help_text="Інструкція до виконання практики", null=True
            ),
        ),
    ]
