# Generated by Django 4.2.20 on 2025-05-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0006_meditation_animation_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="meditation", name="animation_type",),
        migrations.RemoveField(model_name="meditation", name="breathing_pattern",),
        migrations.RemoveField(model_name="meditation", name="instruction",),
        migrations.AddField(
            model_name="meditation",
            name="exhale",
            field=models.PositiveIntegerField(
                blank=True, help_text="Exhale time (sec)", null=True
            ),
        ),
        migrations.AddField(
            model_name="meditation",
            name="hold",
            field=models.PositiveIntegerField(
                blank=True, help_text="Hold time (sec)", null=True
            ),
        ),
        migrations.AddField(
            model_name="meditation",
            name="inhale",
            field=models.PositiveIntegerField(
                blank=True, help_text="Inhale time (sec)", null=True
            ),
        ),
        migrations.AddField(
            model_name="meditation",
            name="rounds",
            field=models.PositiveIntegerField(
                blank=True, help_text="How many rounds", null=True
            ),
        ),
    ]
