# Generated by Django 4.2.20 on 2025-05-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0007_remove_meditation_animation_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="meditation", name="exhale",),
        migrations.RemoveField(model_name="meditation", name="hold",),
        migrations.RemoveField(model_name="meditation", name="inhale",),
        migrations.RemoveField(model_name="meditation", name="rounds",),
        migrations.AddField(
            model_name="meditation",
            name="animation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("circle", "Circle"),
                    ("bar", "Bar"),
                    ("square", "Square"),
                    ("wave", "Wave"),
                ],
                help_text="Тип анімації (наприклад, circle, bar)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meditation",
            name="breathing_pattern",
            field=models.JSONField(
                blank=True,
                help_text='Патерн дихання у форматі {"inhale": 4, "hold": 7, "exhale": 8}',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meditation",
            name="instruction",
            field=models.TextField(
                blank=True,
                help_text="Покрокова інструкція до виконання практики",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="meditation",
            name="duration",
            field=models.PositiveIntegerField(help_text="Тривалість у секундах"),
        ),
    ]
