services:
  - type: web
    name: safeplace-backend
    runtime: python
    repo: https://github.com/ksentin/mental-support-platform.git
    branch: main
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      python -m spacy download uk_core_news_sm
      python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.backend.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: safeplace-db
          property: connectionString
      - key: DEBUG
        value: "False"

databases:
  - name: safeplace-db
    databaseName: safeplace
    user: safeplace_user
