# Generated by Django 4.2.20 on 2025-04-28 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("happy", "Щасливий"),
                            ("smile", "Усміхнений"),
                            ("neutral", "Нейтральний"),
                            ("sad", "Сумний"),
                            ("cry", "Плаче"),
                        ],
                        max_length=10,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("good_things", models.TextField(blank=True)),
                ("bad_things", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mood_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-date"], "unique_together": {("user", "date")},},
        ),
    ]
