# Generated by Django 4.2.20 on 2025-05-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article", name="content", field=models.TextField(blank=True),
        ),
    ]
