# Generated by Django 4.2.20 on 2025-05-17 21:08

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Текст"),
        ),
    ]
